#!/usr/bin/env node
/**
 * Generate src/client/glass-css.js from src/client/glass.css so the tsdown
 * bundle inlines the stylesheet as a plain JS string — no CSS pipeline in the
 * client bundle at all (avoids tsdown/rolldown native CSS handling entirely).
 *
 * Usage: node scripts/gen-css.mjs [--check]
 */

import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const sourcePath = resolve(root, 'src/client/glass.css')
const outPath = resolve(root, 'src/client/glass-css.js')
const checkOnly = process.argv.includes('--check')

async function main() {
  const css = await readFile(sourcePath, 'utf8')
  const generated =
    '// GENERATED by scripts/gen-css.mjs from src/client/glass.css — do not edit.\n'
    + '// Run `npm run gen:css` (or `pnpm gen:css`) after editing the stylesheet.\n'
    + `export default ${JSON.stringify(css)};\n`

  if (checkOnly) {
    let current = ''
    try {
      current = await readFile(outPath, 'utf8')
    } catch {
      /* missing output counts as out of date */
    }
    if (current !== generated) {
      console.error('glass-css.js is out of date. Run: node scripts/gen-css.mjs')
      process.exitCode = 1
      return
    }
    console.log('glass-css.js is up to date.')
    return
  }

  await writeFile(outPath, generated, 'utf8')
  console.log(`Generated ${outPath} (${generated.length} bytes)`)
}

await main()
